[test]
root = "src"
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = ["src/auth/service/auth_proxy.service.ts", "src/config/log-stream.ts"]
